steps:
  # Step 1: Install pnpm
  - name: "node:20"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        corepack enable
        corepack prepare pnpm@latest --activate
        pnpm install

  # Step 2: Build the Next.js app
  - name: "node:20"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        pnpm run build

  # Step 3: Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "next15-app",
        "--source",
        ".",
        "--region",
        "asia-south1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
